language: cpp
sudo: required
dist: bionic
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y g++-7 cmake-data cmake e2fslibs-dev libblkid-dev libcurl-dev
script:
- ./builds/binary.sh
